### PR TITLE
ProjectNode: Adapt to 4.3

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
How about trying to push the plugin upstream? Then changes like this will be handled by the ones who do them...

**Comment by hugopl** [comment]
I have mixed feelings about push it upstream, the good things are:

- get this changes handled by who do them.
- get reviews on code I write for the plugin and be sure I don't use the QtC API the wrong way.

bad things are:
- gerrit.
- the bureaucracy of a project with dozens of developers vs the simplicity of an one-man project.

But I think in the end it would be a good idea, I can do this next week (ask in the mailing list if it's feasible), because probably I'll need to have some free time to adjust things in the project code during the review process and this week I'm a bit busy with my job.

**Comment by orgads** [comment]
Gerrit is fun once you get used to it. I love it :)

Regarding the bureaucracy, from what I know the Creator team is very helpful. The first review might be long (expect discovery of many bugs :)), but later it's usually easy to accept fixes.

Start with converting the file names to lowercase ;)

**Comment by hugopl** [comment]
I used qt-project gerrit years ago when I worked on PySide, I remember the setup was painful but after it was a matter of getting used to it.

I believe this first review will find a lot of bugs and wrong use of the QtC API, this is the thing that most drives me towards try to upstream the code.

Sure, after talking with people and they agree in upstreaming it, I'm going to convert the code to QtC code style/file naming convention/etc... this is the easy part :-)

**Pull request merged**
