### PR TITLE
Adapt to 4.12

### PR DESCRIPTION
**Pull request by orgads**
Compiles, Run doesn't work (targets don't have executables).

### CODE REVIEW

**Comment by orgads** [comment]
Sorry for the delay. I started to work on this very long ago, but stopped at some point.

It "mostly works" with this patch. Run configurations are detected but don't work. I'm not sure why.

**Comment by orgads** [comment]
Fixes #131

**Comment by hugopl** [comment]
Thanks very much... looking at th epatch it seems that really **a lot** of things changed... and seems there's no more two separated entities, a Project a their BuildSystem, now the BuildSystem is the project, makes sense.

**Comment by hugopl** [comment]
I squashed my wip commit into yours and pushed into master. 9e9e4961cd4ad1e15d134b0eabd716a525250a1b

**Pull request closed without merging**
