### PR TITLE
Move file action checks to actual BuildSystem declaration

### PR DESCRIPTION
**Pull request by NickLion**
It seems there is lost BuildSystem declaration, which isn't used anywhere. Without moving this functions (and restoring supportsAction) I can't rename or remove files from project.
(this one with correct access modifiers)

### CODE REVIEW

**Comment by hugopl** [comment]
Very good, I was missing the rename file support

**Comment by hugopl** [comment]
I think is time to rename this file from RubyProject to RubyBuildSystem.

Also... I wrote the first version of this plugin at the time when I was working on WebKit, so I just got the file naming convention from WebKit, maybe we should start using the same QtC file naming convention.

**Comment by orgads** [comment]
Why did you close it?

**Comment by hugopl** [comment]
because I'm stupid :-P, I reviewed it, tested it... closed the ticket... but forgot to merge it. doh!.

**Comment by hugopl** [comment]
I manually merged it now d31989aee6666416e25ac6206746f14b9ac36dce.

**Pull request closed without merging**
