### PR TITLE
Adapt to master

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
Notice that this is for 4.7, not 4.6. So you may prefer to wait until 4.6 is released...

**Comment by hugopl** [comment]
Why do we need to use a d-pointer inthe Plugin class? I mean, why does a plugin would need to care about ABI compatibility?

**Comment by hugopl** [comment]
Yes, I'll wait... and then merge things I did on 4.5 branch with your changes on 4.6.

**Comment by orgads** [comment]
It is not for ABI compat. It's just for avoiding includes for all the headers in plugin.h.

**Comment by hugopl** [comment]
We were already not including all headers on plugin.h, however I liked the change to allocate the plugin objects in the stack instead of the heap using AutoRelease... code got small/simpler.

**Comment by hugopl** [comment]
I'll just wait 4.6 to be released to merge this, thanks very much!

**Pull request merged**
