### PR TITLE
Merge 4.6

### PR DESCRIPTION
**Pull request by orgads**
Initialize rubocop only when opening rb files.

### CODE REVIEW

**Comment by orgads** [comment]
The windows and crash fixes were also meant for 4.6. Did I choose the wrong branch? :)

**Comment by hugopl** [comment]
I think there's nothing on 4.6.0 branch that isn't in master (in term of features), the conflict is because I just accepted a MR to show rubocop stderr on a pane instead of a msgbox.

**Comment by hugopl** [comment]
Oh, yes, the windows fixes!, so yes, make sense to do the merge now, so they will be available on master.

**Comment by orgads** [comment]
No, the difference is because I included a fix in the backport commit.

If rubocop is not installed, the popup message appeared right on startup. I changed it to only be initialized when opening the first rb file.

**Pull request merged**
